FROM ubuntu
LABEL maintainer1="developer1@somewhere.com"
ARG VERSION
ENV VERSION=1.0.0 
ENTRYPOINT exec top -b
WORKDIR /a
WORKDIR b
WORKDIR c
RUN pwd
RUN echo $VERSION
LABEL maintainer="developer@somewhere.com"
HEALTHCHECK --interval=20s --timeout=1s \
CMD exit 1
LABEL maintainer2="developer2@somewhere.com"
